### ISSUE TITLE
Explore moving from wg-quick(8) to wg(8) on the backend

### ISSUE THREAD

**Issue by theonemcdonald** [theonemcdonald/pfSense-pkg-WireGuard#42]
Currently we use wg-quick to interact with WireGuard. This adds two additional dependencies: wg-quick and bash. It is possible to invoke wg directly and not have to deal wg-quick all. This would give us more  explicit control on interface buildup and teardown , etc.

**Comment by Tigger2014** [comment]
Becoming more required due to the wg-quick injecting all or nothing for routes.
This is an issue for when a tunnel specifies a default route as an allowed IP

**Comment by theonemcdonald** [comment]
Notes:

1. Will need to build `wireguard-tools-lite` which only includes `wg(8)`. `make FLAVOR=lite package` works
2. Using -lite eliminates the need for bash.
3. Will need to handle address assignment and route creation manually instead of relying on `wg-quick(8)` to do the dirty work
4. ...

**Comment by zx2c4** [comment]
> Becoming more required due to the wg-quick injecting all or nothing for routes.

FYI, you can specify `Table=off` to disable automatic allowedips->route adding, and then add your own through other means.

> 3. Will need to handle address assignment and route creation manually instead of relying on wg-quick(8) to do the dirty work
> 4. ...

In the case of the default route, you'll want to track the underlying interface's actual default route, as well as route MTU. wg-quick does this with a little backgrounded bash process monitoring the routing table.

**Comment by theonemcdonald** [comment]
Moved to using native tools `wg` `ifconfig` and pfSense builtins.

**Comment by zx2c4** [comment]
I went looking for how you went about reimplementing wg-quick and couldn't actually find anything that replaces its functionality. There's nothing (seemingly?) syncing allowedips to routes, handling optimal pmtu changes, or dealing with circular routing. You'll probably want to re-open this issue into those problems are properly understood and tackled. In the process of looking for that code, I found a few random odd nits maybe you're interested in:

https://github.com/theonemcdonald/pfSense-pkg-WireGuard/blob/86ec3f256f0e046cd36d3059a8effaa275c17578/src/files/usr/local/pkg/wireguard/wg.inc#L685

Every place else calls this "Endpoint", with a lowercase P.

https://github.com/theonemcdonald/pfSense-pkg-WireGuard/blob/86ec3f256f0e046cd36d3059a8effaa275c17578/src/files/usr/local/pkg/wireguard/wg.inc#L704-L706

This is sometimes insecure, since there's a race between the file write and the chmod'ing. You'll really want to, instead, set the umask, or simply create the files with the permissions you want.

https://github.com/theonemcdonald/pfSense-pkg-WireGuard/blob/86ec3f256f0e046cd36d3059a8effaa275c17578/src/files/usr/local/pkg/wireguard/wg.inc#L702

I haven't looked to carefully at what sensitization you do, but note you find yourself in trouble if tunnel['name'] has `../` and such in it. I also don't know where the argument of `write_config` goes, but in case it's echoed somewhere non-escaped, beware.

https://github.com/theonemcdonald/pfSense-pkg-WireGuard/blob/86ec3f256f0e046cd36d3059a8effaa275c17578/src/files/usr/local/pkg/wireguard/wg.inc#L636-L642

Seems to be missing Fwmark.

https://github.com/theonemcdonald/pfSense-pkg-WireGuard/blob/86ec3f256f0e046cd36d3059a8effaa275c17578/src/files/usr/local/pkg/wireguard/wg_api.inc#L427-L435

Here's a regex you can use instead of that: `^[A-Za-z0-9+/]{42}[A|E|I|M|Q|U|Y|c|g|k|o|s|w|4|8|0]=$`. Details are [in this mailing list post](https://lists.zx2c4.com/pipermail/wireguard/2020-December/006222.html).

**Comment by theonemcdonald** [comment]
> I went looking for how you went about reimplementing wg-quick and couldn't actually find anything that replaces its functionality. There's nothing (seemingly?) syncing allowedips to routes, handling optimal pmtu changes, or dealing with circular routing. You'll probably want to re-open this issue until those problems are properly understood and tackled. In the process of looking for that code, I found a few random odd nits maybe you're interested in:

Good point, that was premature on my part. Route handling is coming, pfSense has internals for interacting with routing table. Will need to investigate pmtu changes and circular routing.

> 
> https://github.com/theonemcdonald/pfSense-pkg-WireGuard/blob/86ec3f256f0e046cd36d3059a8effaa275c17578/src/files/usr/local/pkg/wireguard/wg.inc#L685
> 
> Every place else calls this "Endpoint", with a lowercase P.

Thanks

> 
> https://github.com/theonemcdonald/pfSense-pkg-WireGuard/blob/86ec3f256f0e046cd36d3059a8effaa275c17578/src/files/usr/local/pkg/wireguard/wg.inc#L704-L706
> 
> This is sometimes insecure, since there's a race between the file write and the chmod'ing. You'll really want to, instead, set the umask, or simply create the files with the permissions you want.
> 

Thanks

> https://github.com/theonemcdonald/pfSense-pkg-WireGuard/blob/86ec3f256f0e046cd36d3059a8effaa275c17578/src/files/usr/local/pkg/wireguard/wg.inc#L702
> 
> I haven't looked to carefully at what sanitization you do, but note you find yourself in trouble if tunnel['name'] has `../` and such in it. I also don't know where the argument of `write_config` goes, but in case it's echoed somewhere non-escaped, beware.
> 

$tunnel['name'] is automatically generated and isn't user configurable.

> https://github.com/theonemcdonald/pfSense-pkg-WireGuard/blob/86ec3f256f0e046cd36d3059a8effaa275c17578/src/files/usr/local/pkg/wireguard/wg.inc#L636-L642
> 
> Seems to be missing Fwmark.
> 

Thanks though I don't think is applicable in pfSense(?)

> https://github.com/theonemcdonald/pfSense-pkg-WireGuard/blob/86ec3f256f0e046cd36d3059a8effaa275c17578/src/files/usr/local/pkg/wireguard/wg_api.inc#L427-L435
> 
> Here's a regex you can use instead of that: `^[A-Za-z0-9+/]{42}[A|E|I|M|Q|U|Y|c|g|k|o|s|w|4|8|0]=$`. Details are [in this mailing list post](https://lists.zx2c4.com/pipermail/wireguard/2020-December/006222.html).

Awesome thanks

**Comment by zx2c4** [comment]
> Thanks though I don't think is applicable in pfSense(?)

No idea. But it is something that the kernel module accepts and something that `pf` can use. And its information you return here:

https://github.com/theonemcdonald/pfSense-pkg-WireGuard/blob/86ec3f256f0e046cd36d3059a8effaa275c17578/src/files/usr/local/pkg/wireguard/wg_api.inc#L39

**Comment by Tigger2014** [comment]
@theonemcdonald  Whats outstanding on this one, I know were moved away in devel builds

**Comment by theonemcdonald** [comment]
I think just route management. Working on this next.

**Comment by zx2c4** [comment]
Any status with the route management? This is a _major_ shortcoming, and one that's going to inevitably send a lot of users my way complaining that "wireguard doesn't work". Anything I can do to help with this?

**Comment by theonemcdonald** [comment]
I keep getting distracted with other things, though think I understand (though please correct me if I'm off base) what needs to happen technically but obviously it's a juggling game with being very careful not to step on pfSense's toes (or do things that it handles in it's own unique way or do things that it isn't expecting).  Though I suspect the apparent impact of users impacted by this currently is rather small. A common use-case right now in the homelab community is Mullvad and other privacy VPNs which the current tooling works fine for. I am personally running OSPF and BGP in a semi-production state with the current package and kmod code and this works fine too because the routes are handling by FRR.

My current back of the napkin idea is to introduce a column of checkboxes next to the allowed ip repeatables on the peer edit page. If a user wants a route created for a particular entry, they can check it. In the case of WireGuard terminating on an edge device, I think route management should be disabled by default and enabled when it is desired. For instance, going back to the FRR case above, because I have two boxes on both ends for redundancy, I actually don't want WireGuard managing routes for me and I just want allowed ips to act as an ACL only.  So I can see this going both ways, at least for real-world pfSense deployments

**Comment by zx2c4** [comment]
1) Most users probably do want allowedips to be copied to routes.
2) More options usually add more complexity and confusion.

So, what if instead of a column of checkboxes, you just have a single checkbox that is by default _on_ that says "add peer allowedips to routes"?

**Comment by Tigger2014** [comment]
> 1. Most users probably do want allowedips to be copied to routes.

This is certainly true on a end user device however on a firewall/router this actually leads to unexpected things, as a general rule routing is handled by routing protocols rather than the VPN/interface directly.

> 2. More options usually add more complexity and confusion.

Again this is for a firewall not a desktop/laptop, users are expected to have a certain understanding of the technology they are using. Whilst it would be nice to have a one side fits all approach this does not work here.

> So, what if instead of a column of checkboxes, you just have a single checkbox that is by default _on_ that says "add peer allowedips to routes"?

This is certainly an option but we have come across situations where this is actually undesirable as a all or nothing approach. Doing this selectively by ip range is better as it allows the use of allowedips as an ACL and allows the firewall itself to decide the best path for the traffic.

**Comment by Tigger2014** [comment]
@theonemcdonald Can we close this off in favour of keeping #43 open?
