### ISSUE TITLE
Prevent adding Outbound NAT rules for wireguard interfaces

### ISSUE THREAD

**Issue by dhiru1602** [theonemcdonald/pfSense-pkg-WireGuard#91]
**Describe the bug**
When the Outbound NAT is set to automatic or hybrid, pfSense automatically creates outbound rules for the wireguard interfaces. I have a setup where-in I don't require outbound NAT on the wireguard interface. NAT is done on my edge router and I have a multi-site setup.

**To Reproduce**
Create a wireguard interface and enable it and set Outbound NAT mode to Automatic or Hybrid.

**Expected behavior**
I have to manually add a new Do not NAT rule on the wireguard interfaces to prevent Outbound NAT from translating the internal LAN subnet IP addresses to wireguard interface's address. I guess the default behavior should be to not add any outbound rules unless they are manually added. In case of OpenVPN, the outbound NAT has to be manually setup if required.

**Version information (please complete the following information):**
 - PfSense: 2.6.0.a.20210528.0100
 - WireGuard-tools: 1.0.20210424
 - WireGuard-kmod: 0.0.20210503
 - pfSense-pkg-WireGuard: 0.1.1

**Comment by theonemcdonald** [comment]
Because of how pfSense curates the list of networks on assigned interfaces to apply automatic or hybrid rules, there isn't much I can do to work around this. At best I might be able to create those Do not NAT rules automatically, but either way you will have a Do not NAT rule on the list of NAT rules
